const flatListData = [
  {
    key: '1',
    image: require('../../../../naruto.jpeg'),
    detail: 'Đơn nghỉ của bạn đã được xác nhận',
    time: '20:52',
    date: '01/01/2020',
    type: 'verify',
  },
  {
    key: '2',
    image: require('../../../../naruto.jpeg'),
    detail: 'Bạn chưa chấm công',
    time: '08:20',
    date: '01/01/2020',
    type: 'warning',
  },
  {
    key: '3',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
    type: 'confirm',
  },
  {
    key: '4',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '5',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '6',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '7',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '8',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '9',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '10',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '11',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
  {
    key: '12',
    image: require('../../../../naruto.jpeg'),
    detail: 'Vui lòng xác nhận KPI tháng này',
    time: '20:52',
    date: '01/01/2020',
  },
];
export default flatListData;
