export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REMEMBER_ACCOUNT = 'REMEMBER_ACCOUNT';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAILED = 'CHANGE_PASS_FAILED';

export const AUTO_LOGIN = 'AUTO_LOGIN';
export const CHANGE_AUTO_LOGIN = 'CHANGE_AUTO_LOGIN';
export const LOG_OUT = 'LOG_OUT';

export const GET_LIST_ROLES = 'GET_LIST_ROLES';
export const GET_LIST_ROLES_SUCCESS = 'GET_LIST_ROLES_SUCCESS';
export const GET_LIST_ROLES_FAILED = 'GET_LIST_ROLES_FAILED';

export const ADD_STAFF = 'ADD_STAFF';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAILED = 'ADD_STAFF_FAILED';

export const GET_DEVICE_ID = 'GET_DEVICE_ID';

export const CHECK_IN = 'CHECK_IN';
export const CHECK_IN_WIFI = 'CHECK_IN_WIFI';

export const CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS';
export const CHECK_IN_FAILED = 'CHECK_IN_FAILED';

export const CREATE_QR = 'CREATE_QR';
export const CREATE_QR_SUCCESS = 'CREATE_QR_SUCCESS';
export const CREATE_QR_FAILED = 'CREATE_QR_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
