export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REMEMBER_ACCOUNT = 'REMEMBER_ACCOUNT';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAILED = 'CHANGE_PASS_FAILED';

export const AUTO_LOGIN = 'AUTO_LOGIN';
export const CHANGE_AUTO_LOGIN = 'CHANGE_AUTO_LOGIN';
export const LOG_OUT = 'LOG_OUT';

export const GET_LIST_ROLES = 'GET_LIST_ROLES';
export const GET_LIST_ROLES_SUCCESS = 'GET_LIST_ROLES_SUCCESS';
export const GET_LIST_ROLES_FAILED = 'GET_LIST_ROLES_FAILED';

export const ADD_STAFF = 'ADD_STAFF';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAILED = 'ADD_STAFF_FAILED';

export const GET_DEVICE_ID = 'GET_DEVICE_ID';

export const CHECK_IN = 'CHECK_IN';
export const CHECK_IN_WIFI = 'CHECK_IN_WIFI';

export const CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS';
export const CHECK_IN_FAILED = 'CHECK_IN_FAILED';

export const CHECK_OUT_SUCCESS ='CHECK_OUT_SUCCESS'

export const CREATE_QR = 'CREATE_QR';
export const CREATE_QR_SUCCESS = 'CREATE_QR_SUCCESS';
export const CREATE_QR_FAILED = 'CREATE_QR_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const GET_LIST_USERS = 'GET_LIST_USERS';
export const GET_LIST_USERS_SUCCESS = 'GET_LIST_USERS_SUCCESS';
export const GET_LIST_USERS_FAILED = 'GET_LIST_USERS_FAILED';

export const SWITCH_TO_CHECKIN = 'SWITCH_TO_CHECKIN';

export const SET_LATE_EARLY = 'SET_LATE_EARLY';
export const SET_LATE_EARLY_FAILED = 'SET_LATE_EARLY_FAILED';
export const SET_LATE_EARLY_SUCCESS = 'SET_LATE_EARLY_SUCCESS';

export const TAKE_LEAVE = 'TAKE_LEAVE';
export const TAKE_LEAVE_FAILED = 'TAKE_LEAVE_FAILED';
export const TAKE_LEAVE_SUCCESS = 'TAKE_LEAVE_SUCCESS';

export const OVER_TIME = 'OVER_TIME';
export const OVER_TIME_FAILED = 'OVER_TIME_FAILED';
export const OVER_TIME_SUCCESS = 'OVER_TIME_SUCCESS';

export const ADD_MEMBER = 'ADD_MEMBER';
export const KICK_MEMBER = 'KICK_MEMBER';
export const CLEAR_MEMBER = 'CLEAR_MEMBER';

// Notification
export const ADD_USER_ID_DEVICE = 'ADD_USER_ID_DEVICE';
export const ADD_USER_ID_DEVICE_SUCCESS = 'ADD_USER_ID_DEVICE_SUCCESS';
export const ADD_USER_ID_DEVICE_FAILED = 'ADD_USER_ID_DEVICE_FAILED';

export const REMOVE_USER_ID_DEVICE = 'REMOVE_USER_ID_DEVICE';
export const REMOVE_USER_ID_DEVICE_SUCCESS = 'REMOVE_USER_ID_DEVICE_SUCCESS';
export const REMOVE_USER_ID_DEVICE_FAILED = 'REMOVE_USER_ID_DEVICE_FAILED';

export const RESET_CHECK = 'RESET_CHECK';

export const GET_ONE_SIGNAL_ID = 'GET_ONE_SIGNAL_ID';

export const ADD_ASSIGN = 'ADD_ASSIGN';
export const KICK_ASSIGN = 'KICK_ASSIGN';

export const GET_LIST_ASSIGN = 'GET_LIST_ASSIGN';
export const GET_LIST_ASSIGN_FAILED = 'GET_LIST_ASSIGN_FAILED';
export const GET_LIST_ASSIGN_SUCCESS = 'GET_LIST_ASSIGN_SUCCESS';
//change method

export const CHANGETO_CHECKIN = 'CHANGETO_CHECKIN';
export const CHANGETO_CHECKOUT = 'CHANGETO_CHECKOUT';

export const GET_LIST_TEAMS = 'GET_LIST_TEAMS';
export const GET_LIST_TEAMS_FAILED = 'GET_LIST_TEAMS_FAILED';
export const GET_LIST_TEAMS_SUCCESS = 'GET_LIST_TEAMS_SUCCESS';

export const GET_LIST_NOTIFYS = 'GET_LIST_NOTIFYS';
export const GET_LIST_NOTIFYS_FAILED = 'GET_LIST_NOTIFYS_FAILED';
export const GET_LIST_NOTIFYS_SUCCESS = 'GET_LIST_NOTIFYS_SUCCESS';

export const SET_STATUS_OT = 'SET_STATUS_OT';
export const SET_STATUS_OT_FAILED = 'SET_STATUS_OT_FAILED';
export const SET_STATUS_OT_SUCCESS = 'SET_STATUS_OT_SUCCESS';

export const SET_STATUS_BREAK = 'SET_STATUS_BREAK';
export const SET_STATUS_BREAK_FAILED = 'SET_STATUS_BREAK_FAILED';
export const SET_STATUS_BREAK_SUCCESS = 'SET_STATUS_BREAK_SUCCESS';

export const SET_STATUS_LATE_EARLY = 'SET_STATUS_LATE_EARLY';
export const SET_STATUS_LATE_EARLY_FAILED = 'SET_STATUS_LATE_EARLY_FAILED';
export const SET_STATUS_LATE_EARLY_SUCCESS = 'SET_STATUS_LATE_EARLY_SUCCESS';
export const GET_LIST_CHECK = 'GET_LIST_CHECK';
export const GET_LIST_CHECK_FAILED = 'GET_LIST_CHECK_FAILED';
export const GET_LIST_CHECK_SUCCESS = 'GET_LIST_CHECK_SUCCESS';
